# Generated by Django 5.2.6 on 2025-10-08 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('region_name', models.CharField(blank=True, max_length=100)),
                ('region_iso_code', models.CharField(blank=True, max_length=20)),
                ('federal_district', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('user_type', models.CharField(choices=[('tourist', 'Турист'), ('local', 'Местный')], max_length=7)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyTourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_transfer_in_moscow', models.BooleanField(default=False)),
                ('flight_class', models.CharField(choices=[('economy', 'Эконом'), ('business', 'Бизнес')], max_length=50)),
                ('days_in_location', models.IntegerField()),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Благоустроенное жильё (отель/глэмпинг/гостевой дом)'), ('tent', 'Палатка')], max_length=100)),
                ('people_in_room', models.IntegerField()),
                ('meal_type', models.CharField(choices=[('standard', 'Стандартное'), ('vegetarian', 'Вегетарианское')], max_length=50)),
                ('meals_per_day', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('waste_management', models.CharField(choices=[('one_bin', 'Выбрасываю всё вместе в один бак'), ('minimize', 'Минимизирую образование отходов'), ('sort', 'Разделяю по видам')], max_length=255)),
                ('boat_trip_duration', models.CharField(choices=[('3-5h', '3-5 часов'), ('10-11h_8', '10-11 часов (катер до 8 мест)'), ('10-11h_20', '10-11 часов (катер до 20 мест)')], max_length=100)),
                ('helicopter_ride_duration', models.IntegerField(blank=True, null=True)),
                ('helicopter_ride_passengers', models.IntegerField(blank=True, null=True)),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoapp.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecoapp.surveyuser')),
                ('transport_choices', models.ManyToManyField(blank=True, to='ecoapp.transporttype')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Частный дом')], max_length=100)),
                ('people_in_home', models.IntegerField()),
                ('housing_area', models.IntegerField()),
                ('heating_source', models.CharField(choices=[('central', 'Центральное'), ('gas', 'Газ'), ('electric', 'Электричество'), ('wood', 'Дрова'), ('coal', 'Уголь')], max_length=100)),
                ('personal_transport', models.CharField(choices=[('car', 'Легковой автомобиль'), ('jeep', 'Джип'), ('minivan', 'Минивен'), ('none', 'Нет личного транспорта')], max_length=100)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('none', 'Нет личного транспорта')], max_length=50)),
                ('average_mileage_per_month', models.IntegerField()),
                ('public_transport_usage', models.CharField(choices=[('daily', 'Ежедневно'), ('1-3_per_week', '1-3 раза в неделю'), ('rarely', 'Очень редко')], max_length=100)),
                ('flights_in_last_year', models.CharField(choices=[('domestic', 'Внутренний'), ('international', 'Международный'), ('none', 'Не летал самолетом')], max_length=100)),
                ('flight_type', models.CharField(choices=[('economy', 'Эконом'), ('business', 'Бизнес'), ('first_class', 'Первый класс'), ('none', 'Не летал самолетом')], max_length=100)),
                ('waste_management', models.CharField(choices=[('no_sorting', 'Без сортировки'), ('separate_collection', 'Раздельный сбор'), ('composting', 'Компостирование')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecoapp.surveyuser')),
            ],
        ),
        migrations.CreateModel(
            name='TransportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecoapp.transportactivity')),
                ('survey_tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_options', to='ecoapp.surveytourist')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecoapp.tour')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoapp.transporttype')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='transport_choices',
            field=models.ManyToManyField(blank=True, to='ecoapp.transporttype'),
        ),
    ]
