# Generated by Django 5.2.6 on 2026-04-24 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('user_type', models.CharField(blank=True, choices=[('tourist', 'Турист'), ('local', 'Местный житель')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='draft-v1', max_length=32)),
                ('is_active', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-created_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('user_type', models.CharField(blank=True, choices=[('tourist', 'Турист'), ('local', 'Местный житель')], max_length=20)),
                ('trigger_category', models.CharField(blank=True, max_length=64)),
                ('min_total_emission', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='surveylocal',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='surveytourist',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='transporttype',
            options={'ordering': ('type_name',)},
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='surveylocal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='surveylocal',
            name='flights_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveylocal',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='surveytourist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='surveytourist',
            name='tours',
            field=models.ManyToManyField(blank=True, to='ecoapp.tour'),
        ),
        migrations.AddField(
            model_name='surveytourist',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tour',
            name='code',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transportactivity',
            name='code',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transportactivity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transportactivity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transportactivity',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transportoption',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transportoption',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='code',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='surveylocal',
            name='flight_type',
            field=models.CharField(choices=[('economy', 'Эконом'), ('business', 'Бизнес')], default='economy', max_length=100),
        ),
        migrations.AlterField(
            model_name='surveylocal',
            name='flights_in_last_year',
            field=models.CharField(choices=[('none', 'Не летаю'), ('domestic', 'Внутренние перелеты'), ('international', 'Международные перелеты')], max_length=100),
        ),
        migrations.AlterField(
            model_name='surveylocal',
            name='fuel_type',
            field=models.CharField(choices=[('none', 'Нет личного транспорта'), ('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электричество'), ('hybrid', 'Гибрид')], max_length=50),
        ),
        migrations.AlterField(
            model_name='surveylocal',
            name='personal_transport',
            field=models.CharField(choices=[('none', 'Нет личного транспорта'), ('car', 'Легковой автомобиль'), ('jeep', 'Внедорожник'), ('minivan', 'Микроавтобус')], max_length=100),
        ),
        migrations.AlterField(
            model_name='surveylocal',
            name='public_transport_usage',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('1_3_per_week', '1-3 раза в неделю'), ('rarely', 'Редко')], max_length=100),
        ),
        migrations.AlterField(
            model_name='surveylocal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_surveys', to='ecoapp.surveyuser'),
        ),
        migrations.AlterField(
            model_name='surveytourist',
            name='accommodation_type',
            field=models.CharField(choices=[('hotel', 'Отель'), ('glamping', 'Глэмпинг'), ('guest_house', 'Гостевой дом'), ('eco_lodge', 'Эко-лодж'), ('tent', 'Палатка')], max_length=100),
        ),
        migrations.AlterField(
            model_name='surveytourist',
            name='boat_trip_duration',
            field=models.CharField(blank=True, choices=[('none', 'Не использовал'), ('3_5h', '3-5 часов'), ('10_11h_8', '10-11 часов, катер до 8 мест'), ('10_11h_20', '10-11 часов, катер до 20 мест')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='surveytourist',
            name='meal_type',
            field=models.CharField(choices=[('standard', 'Стандартное'), ('vegetarian', 'Вегетарианское'), ('local', 'Локальные продукты')], max_length=50),
        ),
        migrations.AlterField(
            model_name='surveytourist',
            name='meals_per_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='surveytourist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_surveys', to='ecoapp.surveyuser'),
        ),
        migrations.AlterField(
            model_name='surveytourist',
            name='waste_management',
            field=models.CharField(choices=[('one_bin', 'Выбрасываю все вместе'), ('minimize', 'Минимизирую отходы'), ('sort', 'Сортирую отходы')], max_length=255),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('tourist', 'Турист'), ('local', 'Местный житель')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transportoption',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecoapp.transportactivity'),
        ),
        migrations.AlterField(
            model_name='transportoption',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecoapp.tour'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_duration_days', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('transport_modes', models.ManyToManyField(blank=True, related_name='routes', to='ecoapp.transporttype')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('anonymized_user_id', models.CharField(db_index=True, max_length=128)),
                ('source', models.CharField(choices=[('web', 'Веб-сайт'), ('telegram', 'Telegram')], max_length=20)),
                ('user_type', models.CharField(choices=[('tourist', 'Турист'), ('local', 'Местный житель')], max_length=20)),
                ('answers', models.JSONField(default=dict)),
                ('breakdown', models.JSONField(default=dict)),
                ('total_emission', models.FloatField()),
                ('recommendation_codes', models.JSONField(blank=True, default=list)),
                ('recommendation_text', models.TextField(blank=True)),
                ('report', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecoapp.checklist')),
                ('factor_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecoapp.factorset')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecoapp.route')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='surveytourist',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecoapp.route'),
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=64)),
                ('subtype', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('is_temporary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('factor_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='ecoapp.factorset')),
            ],
            options={
                'ordering': ('category', 'subtype'),
                'unique_together': {('factor_set', 'category', 'subtype')},
            },
        ),
    ]
